### PR TITLE
Fix notifications daemon

### LINKED ISSUE #659: [Notifications] Daemon stop work on config update
When I update config file in ~/.config/ashell notifications daemon stop work. It doesn't handle and display notifications

### PR DESCRIPTION
**Pull request by denqxotl**
Closes #659

### CODE REVIEW

File: src/services/notifications/dbus.rs [hunk 1]
```diff
@@ -172,10 +180,13 @@ impl NotificationDaemon {
 
         let dbus_proxy = DBusProxy::new(&connection).await?;
         let flags = RequestNameFlags::AllowReplacement.into();
-        if dbus_proxy.request_name(NAME, flags).await? == RequestNameReply::InQueue {
```
Comment (MalpenZibo) [inline src/services/notifications/dbus.rs]: Maybe we could avoid the `OnceCell` using `ReplaceExisting`. The Tray service as a similar solution could you check and try to understand if the `ReplaceExisting` resolve the issue?

Comment (denqxotl) [reply src/services/notifications/dbus.rs]: sure

**Review by MalpenZibo — APPROVED** [review]
🚀
